#!/bin/bash
set -e -u

_fail() {
    echo 1>&2 "$1"
    exit 255
}

exec docker run $(compgen -A variable | grep -E -v "^(PATH)$" | awk "{print \"--env\", \$1}") --interactive --net host --rm --tty="$([ -t 0 ] && echo "true" || echo "false")" --user "$(id -u)" --volume /etc/group:/etc/group:ro --volume /etc/localtime:/etc/localtime:ro --volume /etc/passwd:/etc/passwd:ro --volume /etc/timezone:/etc/timezone:ro --volume /run:/run --volume /tmp:/tmp --volume "${HOME}":"${HOME}" --volume "${PWD}":"${PWD}" --workdir "${PWD}" "${IMAGE:-composer}":"${TAG:-latest}" "$(basename "$0")" "$@"

