#!/bin/bash

### BEGIN INIT INFO
# Provides:          postgresql
# Required-Start:    $docker
# Required-Stop:     $docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       PostgreSQL RDBMS server
### END INIT INFO

set -e

CONTAINER_NAME="postgresql"
CONTAINER_OPTIONS="--net host -v /srv/postgresql:/var/lib/postgresql/data"
IMAGE="postgres"
TAG="9.4"
[[ -f /etc/default/postgresql ]] && . /etc/default/postgresql

. /lib/lsb/init-functions

do_start() {
    docker inspect $CONTAINER_NAME >/dev/null 2>&1 && do_stop || :

    docker run \
        -d \
        --name $CONTAINER_NAME \
        -v /etc/localtime:/etc/localtime:ro \
        $CONTAINER_OPTIONS \
        $IMAGE:$TAG >/dev/null 2>&1
}

do_stop() {
    docker rm -f $CONTAINER_NAME >/dev/null 2>&1
}

is_started() {
    [[ $(docker inspect --format "{{ .State.Running }}" $CONTAINER_NAME 2>/dev/null) == true ]]
}

is_stopped() {
    ! is_started
}

case "$1" in
    start)
        if is_started ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is already started."
        else
            do_start
            log_daemon_msg "The container '$CONTAINER_NAME' is started."
        fi
    ;;

    stop)
        if is_stopped ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is already stopped."
        else
            do_stop
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi
    ;;

    restart)
        if is_started ; then
            do_stop
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi

        do_start
        log_daemon_msg "The container '$CONTAINER_NAME' is started."
    ;;

    status)
        if is_started ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is started."
        else
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi
    ;;

    *)
        log_action_msg "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
