#!/bin/bash

### BEGIN INIT INFO
# Provides:          vsftpd
# Required-Start:    $docker
# Required-Stop:     $docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Very Secure FTP Daemon
# Description:       Provides a lightweight, efficient FTP server written for security.
### END INIT INFO

set -e

CONTAINER_NAME="vsftpd"
CONTAINER_OPTIONS="--net host -v /srv/ftp:/srv/ftp"
VSFTPD_OPTIONS="-oanonymous_enable=YES -osecure_chroot_dir=/srv/ftp"
IMAGE="mauchede/vsftpd"
TAG="3.0.2"
[[ -f /etc/default/vsftpd ]] && . /etc/default/vsftpd

. /lib/lsb/init-functions

do_start() {
    docker inspect $CONTAINER_NAME >/dev/null 2>&1 && do_stop || :

    docker run \
        -d \
        --name $CONTAINER_NAME \
        $CONTAINER_OPTIONS \
        $IMAGE:$TAG $VSFTPD_OPTIONS >/dev/null 2>&1
}

do_stop() {
    docker rm -f $CONTAINER_NAME >/dev/null 2>&1
}

is_started() {
    [[ $(docker inspect --format "{{ .State.Running }}" $CONTAINER_NAME 2>/dev/null) == true ]]
}

is_stopped() {
    ! is_started
}

case "$1" in
    start)
        if is_started ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is already started."
        else
            do_start
            log_daemon_msg "The container '$CONTAINER_NAME' is started."
        fi
    ;;

    stop)
        if is_stopped ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is already stopped."
        else
            do_stop
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi
    ;;

    restart)
        if is_started ; then
            do_stop
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi

        do_start
        log_daemon_msg "The container '$CONTAINER_NAME' is started."
    ;;

    status)
        if is_started ; then
            log_daemon_msg "The container '$CONTAINER_NAME' is started."
        else
            log_daemon_msg "The container '$CONTAINER_NAME' is stopped."
        fi
    ;;

    *)
        log_action_msg "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
