#!/bin/bash

if [ "$#" -lt 2 ] ; then
    echo 1>&2 "Invalid number of arguments."
    echo 1>&2 "Usage: $(basename "$0") [USER] [...]"
    exit 1
fi

sudo --user "$1" -- bash << EOF
    export XDG_RUNTIME_DIR="/run/user/\${UID}"
    export DBUS_SESSION_BUS_ADDRESS="unix:path=\${XDG_RUNTIME_DIR}/bus"

    systemctl --user ${@:2}
EOF
